[task]
id          = "atlas-sus-16-15_sim-T2tt_SRA-T0"
paper       = "ATLAS-SUS-16-15"
type        = "simulation"
target      = "T2tt_1000_1"
observable  = "MT2"

[metadata]
difficulty = "hard"
walltime   = "2h30m"
tags       = ["SUSY", "ATLAS", "stops", "13TeV", "simplified model"]

[metrics]
tolerance = 0.05
mode = "shape_norm"
plot = "Events/bin"
report = ["relative_l2", "delta"]
