dependent_variables:
- header: {name: T5Wg_1600_100}
  values:
  - {value: 0.4}
  - {value: 0.8}
  - {value: 0.7}
independent_variables:
- header: {name: PTMISS, units: GEV}
  values:
  - {low: 350.0, high: 450.0}
  - {low: 450.0, high: 600.0}
  - {low: 600.0, high: 800.0}
