dependent_variables:
- header: {name: T5Wg_1600_100}
  values:
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.0}
  - {value: 0.4}
  - {value: 0.8}
  - {value: 0.7}
independent_variables:
- header: {name: PTMISS, units: GEV}
  values:
  - {low: 0.0, high: 10.0}
  - {low: 10.0, high: 20.0}
  - {low: 20.0, high: 30.0}
  - {low: 30.0, high: 40.0}
  - {low: 40.0, high: 50.0}
  - {low: 50.0, high: 60.0}
  - {low: 60.0, high: 70.0}
  - {low: 70.0, high: 80.0}
  - {low: 80.0, high: 90.0}
  - {low: 90.0, high: 100.0}
  - {low: 100.0, high: 110.0}
  - {low: 110.0, high: 120.0}
  - {low: 120.0, high: 130.0}
  - {low: 130.0, high: 140.0}
  - {low: 140.0, high: 150.0}
  - {low: 150.0, high: 160.0}
  - {low: 160.0, high: 170.0}
  - {low: 170.0, high: 180.0}
  - {low: 180.0, high: 190.0}
  - {low: 190.0, high: 200.0}
  - {low: 200.0, high: 250.0}
  - {low: 250.0, high: 300.0}
  - {low: 300.0, high: 350.0}
  - {low: 350.0, high: 450.0}
  - {low: 450.0, high: 600.0}
  - {low: 600.0, high: 800.0}
