dependent_variables:
- header: {name: T5Wg_1750_1700}
  values:
  - {value: 0.49}
  - {value: 1.78}
  - {value: 6.10}
  - {value: 46.48}
independent_variables:
- header: {name: STGAMMA, units: GEV}
  values:
  - {low: 600.0, high: 800.0}
  - {low: 800.0, high: 1000.0}
  - {low: 1000.0, high: 1300.0}
  - {low: 1300.0, high: 1600.0}
